import { PT, Athlete, GalleryItem, Review, Specialization, CoachingPackage } from '../types';

const makeAvatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=random&size=200`;

const makeGallery = (ptId: string): GalleryItem[] => [
  {
    id: `${ptId}_g1`,
    beforeImage: `https://picsum.photos/seed/${ptId}1/400/300`,
    afterImage: `https://picsum.photos/seed/${ptId}2/400/300`,
    description: '3 aylık antrenman programı sonucu',
    studentName: 'Mehmet A.',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: `${ptId}_g2`,
    beforeImage: `https://picsum.photos/seed/${ptId}3/400/300`,
    afterImage: `https://picsum.photos/seed/${ptId}4/400/300`,
    description: '6 aylık dönüşüm programı',
    studentName: 'Fatma B.',
    createdAt: new Date('2024-02-20'),
  },
];

const makePackages = (
  id: string,
  starterPrice: number,
  midPrice: number,
  proPrice: number,
  starterFeatures: string[],
  midFeatures: string[],
  proFeatures: string[],
  starterSessions = 2,
  midSessions = 3,
  proSessions = 4,
): CoachingPackage[] => [
  {
    id: `${id}_pkg_starter`,
    level: 'starter',
    name: 'Başlangıç',
    price: starterPrice,
    durationWeeks: 4,
    sessionsPerWeek: starterSessions,
    features: starterFeatures,
  },
  {
    id: `${id}_pkg_mid`,
    level: 'intermediate',
    name: 'Orta Seviye',
    price: midPrice,
    durationWeeks: 8,
    sessionsPerWeek: midSessions,
    features: midFeatures,
    isPopular: true,
  },
  {
    id: `${id}_pkg_pro`,
    level: 'professional',
    name: 'Profesyonel',
    price: proPrice,
    durationWeeks: 12,
    sessionsPerWeek: proSessions,
    features: proFeatures,
  },
];

export const MOCK_PTS: PT[] = [
  {
    id: 'pt_ahmet',
    email: 'devrimpt@test.com',
    firstName: 'Ahmet',
    lastName: 'Yılmaz',
    userType: 'pt',
    avatar: makeAvatar('Ahmet Yılmaz'),
    createdAt: new Date('2023-01-10'),
    bio: 'ACSM sertifikalı kişisel antrenör olarak 8 yıldır sporcularımın kas geliştirme ve fonksiyonel fitness hedeflerine ulaşmalarına yardımcı oluyorum. Bilimsel temelli antrenman programları ve beslenme takibiyle kalıcı sonuçlar elde etmenizi sağlıyorum.',
    specializations: ['muscle_gain', 'functional'] as Specialization[],
    certificates: 'ACSM Certified Personal Trainer, NSCA-CPT, TFF Antrenör Lisansı',
    experienceYears: 8,
    packages: makePackages(
      'pt_ahmet',
      1800, 3600, 5200,
      ['Kişiselleştirilmiş antrenman programı', 'Haftalık ilerleme takibi', 'Temel beslenme rehberi', 'WhatsApp desteği'],
      ['Kişiselleştirilmiş antrenman & beslenme programı', 'Haftalık video analizi', '7/24 mesajlaşma desteği', 'Aylık vücut ölçüm raporu', 'Antrenman videoları'],
      ['Tam kişiselleştirilmiş program', 'Günlük ilerleme takibi', 'Özel beslenme planı', '7/24 öncelikli destek', 'Aylık birebir görüntülü seans', 'Supplement rehberi', 'Yarışma hazırlık desteği'],
    ),
    rating: 4.9,
    reviewCount: 47,
    students: ['athlete_student1', 'athlete_student2', 'athlete_student3'],
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('ahmet'),
    reviews: [
      {
        id: 'rev_a1',
        athleteId: 'ath1',
        athleteName: 'Kemal Yıldız',
        athleteAvatar: makeAvatar('Kemal Yıldız'),
        rating: 5,
        comment: 'Ahmet hoca gerçekten işinde uzman. 3 ayda hedeflerime ulaştım, programları çok sistematik ve bilimsel.',
        createdAt: new Date('2024-03-10'),
      },
      {
        id: 'rev_a2',
        athleteId: 'ath2',
        athleteName: 'Seda Kılıç',
        athleteAvatar: makeAvatar('Seda Kılıç'),
        rating: 5,
        comment: 'Motivasyonu ve bilgisiyle beni çok geliştirdi. Kesinlikle tavsiye ederim!',
        createdAt: new Date('2024-02-28'),
      },
      {
        id: 'rev_a3',
        athleteId: 'ath3',
        athleteName: 'Tarık Öztürk',
        athleteAvatar: makeAvatar('Tarık Öztürk'),
        rating: 5,
        comment: 'Her antrenman seansı planlı ve verimli. Sorularıma hep cevap veriyor.',
        createdAt: new Date('2024-01-15'),
      },
    ],
  },
  {
    id: 'pt_zeynep',
    email: 'zeynep.kaya@fitcoach.com',
    firstName: 'Zeynep',
    lastName: 'Kaya',
    userType: 'pt',
    avatar: makeAvatar('Zeynep Kaya'),
    createdAt: new Date('2022-06-15'),
    bio: 'Kilo yönetimi ve sağlıklı beslenme konusunda 6 yıllık deneyimli bir koçum. Müşterilerime özel diyet programları ve kardiyo antrenmanları hazırlayarak uzun vadeli sağlıklı yaşam alışkanlıkları kazandırıyorum.',
    specializations: ['weight_loss', 'nutrition'] as Specialization[],
    certificates: 'ACE Certified Personal Trainer, Precision Nutrition Level 1, ISSA Nutrition Coach',
    experienceYears: 6,
    packages: makePackages(
      'pt_zeynep',
      1500, 3000, 5500,
      ['Kişisel beslenme planı', 'Haftada 2 kardiyo seansı', 'Kilo takip tablosu', 'E-posta desteği'],
      ['Özel beslenme & egzersiz planı', 'Haftalık takip seansı', 'Yemek günlüğü analizi', 'Alışveriş listesi & tarifler', '7/24 mesajlaşma'],
      ['Tam kapsamlı kilo yönetimi', 'Günlük beslenme takibi', 'Metabolizma analizi', 'Hormonal denge rehberi', '7/24 öncelikli destek', 'Aylık birebir danışmanlık'],
      2, 3, 5,
    ),
    rating: 4.8,
    reviewCount: 63,
    students: Array.from({ length: 8 }, (_, i) => `student_z${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('zeynep'),
    reviews: [
      {
        id: 'rev_z1',
        athleteId: 'ath4',
        athleteName: 'Aylin Şimşek',
        athleteAvatar: makeAvatar('Aylin Şimşek'),
        rating: 5,
        comment: 'Zeynep hanım sayesinde 4 ayda 12 kilo verdim. Hem egzersiz hem de beslenme programım mükemmeldi.',
        createdAt: new Date('2024-03-05'),
      },
      {
        id: 'rev_z2',
        athleteId: 'ath5',
        athleteName: 'Bülent Aydın',
        athleteAvatar: makeAvatar('Bülent Aydın'),
        rating: 5,
        comment: 'Beslenme konusundaki bilgisi inanılmaz. Sağlıklı yemek yemeyi öğretti.',
        createdAt: new Date('2024-02-10'),
      },
      {
        id: 'rev_z3',
        athleteId: 'ath6',
        athleteName: 'Ceren Doğan',
        athleteAvatar: makeAvatar('Ceren Doğan'),
        rating: 4,
        comment: 'Çok sabırlı ve anlayışlı bir hoca. Programları kişiye özel hazırlanıyor.',
        createdAt: new Date('2024-01-20'),
      },
    ],
  },
  {
    id: 'pt_mert',
    email: 'mert.demir@fitcoach.com',
    firstName: 'Mert',
    lastName: 'Demir',
    userType: 'pt',
    avatar: makeAvatar('Mert Demir'),
    createdAt: new Date('2021-09-01'),
    bio: 'Fonksiyonel antrenman ve rehabilitasyon alanında uzmanlaşmış, 10 yıllık deneyimli bir spor fizyoterapisti ve kişisel antrenörüm. Yaralanma sonrası iyileşme süreçlerinde ve atletik performans geliştirmede güvenilir sonuçlar sunuyorum.',
    specializations: ['functional', 'rehabilitation'] as Specialization[],
    certificates: 'NSCA-CSCS, FMS Level 2, Spor Fizyoterapisi Sertifikası, TFF A Lisansı',
    experienceYears: 10,
    packages: makePackages(
      'pt_mert',
      2000, 4000, 6500,
      ['Hareket analizi & değerlendirme', 'Haftada 2 fonksiyonel seans', 'Temel yaralanma önleme programı', 'Egzersiz rehberi'],
      ['Kapsamlı hareket değerlendirmesi', 'Kişisel rehabilitasyon programı', 'Haftalık ilerleme ölçümü', 'Mobilite & esneklik çalışması', '7/24 mesajlaşma desteği'],
      ['Tam rehabilitasyon & performans programı', 'Günlük takip', 'Fizyoterapi odaklı egzersizler', 'Sporcu performans analizi', '7/24 öncelikli destek', 'Aylık birebir değerlendirme'],
    ),
    rating: 4.7,
    reviewCount: 89,
    students: Array.from({ length: 5 }, (_, i) => `student_m${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('mert'),
    reviews: [
      {
        id: 'rev_m1',
        athleteId: 'ath7',
        athleteName: 'Onur Yıldırım',
        athleteAvatar: makeAvatar('Onur Yıldırım'),
        rating: 5,
        comment: 'Diz ameliyatı sonrası Mert hocanın programıyla 3 ayda koşmaya başladım. Harika bir rehber.',
        createdAt: new Date('2024-03-12'),
      },
      {
        id: 'rev_m2',
        athleteId: 'ath8',
        athleteName: 'Gizem Arslan',
        athleteAvatar: makeAvatar('Gizem Arslan'),
        rating: 5,
        comment: 'Fonksiyonel hareketler konusunda gerçekten uzman. Her seansım farklı ve eğlenceli.',
        createdAt: new Date('2024-02-18'),
      },
      {
        id: 'rev_m3',
        athleteId: 'ath9',
        athleteName: 'Hasan Kaya',
        athleteAvatar: makeAvatar('Hasan Kaya'),
        rating: 4,
        comment: 'Fiyatı biraz yüksek ama aldığınız hizmet kaliteli. Kesinlikle tavsiye ederim.',
        createdAt: new Date('2024-01-08'),
      },
    ],
  },
  {
    id: 'pt_selin',
    email: 'selin.arslan@fitcoach.com',
    firstName: 'Selin',
    lastName: 'Arslan',
    userType: 'pt',
    avatar: makeAvatar('Selin Arslan'),
    createdAt: new Date('2020-03-15'),
    bio: 'Yoga ve Pilates alanında sertifikalı bir instructor olarak 7 yıldır öğrencilerimin hem bedensel hem de zihinsel gelişimine destek oluyorum. Nefes teknikleri ve esneklik çalışmalarıyla bütünsel bir sağlık anlayışı sunuyorum.',
    specializations: ['yoga', 'pilates'] as Specialization[],
    certificates: 'RYT-500 Yoga Alliance, Stott Pilates Certified, Mindfulness Instructor',
    experienceYears: 7,
    packages: makePackages(
      'pt_selin',
      1200, 2400, 4200,
      ['Temel yoga & pilates dersleri', 'Haftada 3 online seans', 'Nefes teknikleri rehberi', 'Meditasyon başlangıç kiti'],
      ['Kişisel yoga & pilates programı', 'Haftada 4 canlı seans', 'Postür değerlendirmesi', 'Mindfulness egzersizleri', 'Haftalık ilerleme görüşmesi'],
      ['Premium bütünsel sağlık programı', 'Haftada 5 birebir seans', 'Tam postür & hareket analizi', 'Kişisel meditasyon programı', 'Ayurveda beslenme tavsiyeleri', '7/24 destek'],
      3, 4, 5,
    ),
    rating: 4.9,
    reviewCount: 112,
    students: Array.from({ length: 10 }, (_, i) => `student_s${i}`),
    maxStudents: 10,
    isAvailable: false,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('selin'),
    reviews: [
      {
        id: 'rev_s1',
        athleteId: 'ath10',
        athleteName: 'Elif Yılmaz',
        athleteAvatar: makeAvatar('Elif Yılmaz'),
        rating: 5,
        comment: 'Selin hoca hayatımı değiştirdi. Hem fiziksel hem de mental olarak çok daha iyi hissediyorum.',
        createdAt: new Date('2024-03-15'),
      },
      {
        id: 'rev_s2',
        athleteId: 'ath11',
        athleteName: 'Merve Öztürk',
        athleteAvatar: makeAvatar('Merve Öztürk'),
        rating: 5,
        comment: 'Pilates derslerinde her şeyi çok iyi anlatıyor. Sırt ağrılarım tamamen geçti!',
        createdAt: new Date('2024-02-25'),
      },
      {
        id: 'rev_s3',
        athleteId: 'ath12',
        athleteName: 'Deniz Çelik',
        athleteAvatar: makeAvatar('Deniz Çelik'),
        rating: 5,
        comment: 'Yoga seansları gerçekten dinlendirici ve dönüştürücü. Çok şanslıyım ki Selin hocayla çalıştım.',
        createdAt: new Date('2024-01-30'),
      },
      {
        id: 'rev_s4',
        athleteId: 'ath13',
        athleteName: 'Ahmet Korkmaz',
        athleteAvatar: makeAvatar('Ahmet Korkmaz'),
        rating: 5,
        comment: 'Eşsiz bir enerji ve bilgi birikimine sahip. Her öğrencisine özel yaklaşım gösteriyor.',
        createdAt: new Date('2024-01-10'),
      },
    ],
  },
  {
    id: 'pt_burak',
    email: 'burak.sahin@fitcoach.com',
    firstName: 'Burak',
    lastName: 'Şahin',
    userType: 'pt',
    avatar: makeAvatar('Burak Şahin'),
    createdAt: new Date('2019-11-20'),
    bio: 'Vücut geliştirme ve kilo yönetimi konusunda 12 yıllık deneyimli bir elit kişisel antrenörüm. Ulusal düzeyde yarışmacı olma deneyimimle sporcularımı en üst performans düzeylerine taşıyorum.',
    specializations: ['muscle_gain', 'weight_loss'] as Specialization[],
    certificates: 'ISSA Elite Trainer, NASM-CPT, Türkiye Bodybuilding Şampiyonu 2018',
    experienceYears: 12,
    packages: makePackages(
      'pt_burak',
      2400, 4800, 8400,
      ['Elite antrenman programı', 'Haftada 2 yoğun seans', 'Vücut kompozisyon ölçümü', 'Supplement tavsiyesi'],
      ['Yarı-elite transformation programı', 'Haftada 3 yoğun seans', 'Beslenme protokolü', 'Haftalık fotoğraflı takip', '7/24 mesajlaşma'],
      ['Full Elite Transformation', 'Haftada 5 birebir seans', 'Kişisel beslenme & supplement planı', 'Günlük takip & koçluk', 'Yarışma hazırlık desteği', 'Özel çalışma planı', '7/24 öncelikli erişim'],
      2, 3, 5,
    ),
    rating: 4.6,
    reviewCount: 38,
    students: Array.from({ length: 2 }, (_, i) => `student_b${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('burak'),
    reviews: [
      {
        id: 'rev_b1',
        athleteId: 'ath14',
        athleteName: 'Volkan Taş',
        athleteAvatar: makeAvatar('Volkan Taş'),
        rating: 5,
        comment: 'Burak hocanın programları çok yoğun ama sonuçları inanılmaz. 5 ayda istediğim vücuda kavuştum.',
        createdAt: new Date('2024-03-08'),
      },
      {
        id: 'rev_b2',
        athleteId: 'ath15',
        athleteName: 'Cem Aydın',
        athleteAvatar: makeAvatar('Cem Aydın'),
        rating: 4,
        comment: 'Ciddi sonuç istiyorsanız bu hoca sizin için. Pahalı ama değer.',
        createdAt: new Date('2024-02-05'),
      },
      {
        id: 'rev_b3',
        athleteId: 'ath16',
        athleteName: 'Murat Güneş',
        athleteAvatar: makeAvatar('Murat Güneş'),
        rating: 5,
        comment: 'Motivasyon konusunda müthiş. Hiç vazgeçmeme engel oldu.',
        createdAt: new Date('2024-01-22'),
      },
    ],
  },
  {
    id: 'pt_elif',
    email: 'elif.celik@fitcoach.com',
    firstName: 'Elif',
    lastName: 'Çelik',
    userType: 'pt',
    avatar: makeAvatar('Elif Çelik'),
    createdAt: new Date('2021-04-10'),
    bio: 'Pilates ve rehabilitasyon alanında uzmanlaşmış, fizyoterapi geçmişine sahip bir kişisel antrenörüm. Kronik ağrılar, postür bozuklukları ve ameliyat sonrası iyileşme süreçlerinde güvenli ve etkili programlar sunuyorum.',
    specializations: ['pilates', 'rehabilitation'] as Specialization[],
    certificates: 'BASI Pilates Certified, Fizyoterapi Lisansı, PRI Level 1',
    experienceYears: 5,
    packages: makePackages(
      'pt_elif',
      1400, 2800, 4800,
      ['Postür analizi & değerlendirme', 'Haftada 2 pilates seansı', 'Temel rehabilitasyon egzersizleri', 'Ev programı'],
      ['Kişisel rehabilitasyon programı', 'Haftada 3 pilates seansı', 'Kronik ağrı yönetimi', 'Haftalık ilerleme ölçümü', 'E-posta & mesajlaşma desteği'],
      ['Tam kapsamlı rehabilitasyon & pilates', 'Haftada 4 birebir seans', 'Fizyoterapi odaklı özel program', 'Günlük takip', '7/24 destek', 'Aylık değerlendirme raporu'],
    ),
    rating: 4.8,
    reviewCount: 56,
    students: Array.from({ length: 7 }, (_, i) => `student_e${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('elif'),
    reviews: [
      {
        id: 'rev_e1',
        athleteId: 'ath17',
        athleteName: 'Neslihan Yıldız',
        athleteAvatar: makeAvatar('Neslihan Yıldız'),
        rating: 5,
        comment: 'Bel fıtığım için başladığım pilates programı sonunda ağrılarım büyük ölçüde azaldı.',
        createdAt: new Date('2024-03-01'),
      },
      {
        id: 'rev_e2',
        athleteId: 'ath18',
        athleteName: 'Serkan Kara',
        athleteAvatar: makeAvatar('Serkan Kara'),
        rating: 5,
        comment: 'Elif hoca hem çok bilgili hem de çok sabırlı. Her egzersizi neden yaptığımızı açıklıyor.',
        createdAt: new Date('2024-02-12'),
      },
      {
        id: 'rev_e3',
        athleteId: 'ath19',
        athleteName: 'Pınar Şen',
        athleteAvatar: makeAvatar('Pınar Şen'),
        rating: 5,
        comment: 'Doğum sonrası diastaz için çalıştım. İnanılmaz sonuçlar aldım. Teşekkürler!',
        createdAt: new Date('2024-01-28'),
      },
    ],
  },
  {
    id: 'pt_oguzhan',
    email: 'oguzhan.koc@fitcoach.com',
    firstName: 'Oğuzhan',
    lastName: 'Koç',
    userType: 'pt',
    avatar: makeAvatar('Oğuzhan Koç'),
    createdAt: new Date('2022-01-05'),
    bio: 'Beslenme bilimi ve kilo yönetimi konusunda akademik eğitim almış, 4 yıllık deneyimli bir diyetisyen koçuyum. Sürdürülebilir kilo kaybı için kişiselleştirilmiş beslenme planları ve egzersiz programları hazırlıyorum.',
    specializations: ['nutrition', 'weight_loss'] as Specialization[],
    certificates: 'Diyetisyen Lisansı (Hacettepe Ü.), Precision Nutrition Level 2, ACE Fitness Nutrition Specialist',
    experienceYears: 4,
    packages: makePackages(
      'pt_oguzhan',
      1700, 3200, 5600,
      ['Temel beslenme analizi', 'Haftada 2 check-in', 'Kişisel diyet planı', 'Yemek takip rehberi'],
      ['Kapsamlı beslenme & egzersiz programı', 'Haftalık 1:1 görüntülü danışmanlık', 'Metabolizma değerlendirmesi', 'Özel tarifler & yemek planı', '7/24 mesajlaşma desteği'],
      ['Premium Diyetisyen Koçluğu', 'Günlük beslenme takibi', 'Kan değerleri analizi rehberi', 'Mikro & makro besin optimizasyonu', '7/24 öncelikli destek', 'Aylık kapsamlı raporlama'],
    ),
    rating: 4.5,
    reviewCount: 29,
    students: Array.from({ length: 6 }, (_, i) => `student_o${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('oguzhan'),
    reviews: [
      {
        id: 'rev_og1',
        athleteId: 'ath20',
        athleteName: 'Zeynep Aktaş',
        athleteAvatar: makeAvatar('Zeynep Aktaş'),
        rating: 5,
        comment: 'Beslenme konusundaki yaklaşımı çok bilimsel ve pratik. Hayatımda ilk kez sürdürülebilir bir diyet yapıyorum.',
        createdAt: new Date('2024-02-28'),
      },
      {
        id: 'rev_og2',
        athleteId: 'ath21',
        athleteName: 'Emre Yılmaz',
        athleteAvatar: makeAvatar('Emre Yılmaz'),
        rating: 4,
        comment: 'Program takibi çok iyi, haftalık check-in seansları motivasyonu artırıyor.',
        createdAt: new Date('2024-02-02'),
      },
      {
        id: 'rev_og3',
        athleteId: 'ath22',
        athleteName: 'Tuğba Güler',
        athleteAvatar: makeAvatar('Tuğba Güler'),
        rating: 4,
        comment: 'Yemek planları gerçekten uygulanabilir ve lezzetli. Artık sağlıklı yemek sıkıcı gelmiyor.',
        createdAt: new Date('2024-01-14'),
      },
    ],
  },
  {
    id: 'pt_ayse',
    email: 'ayse.turk@fitcoach.com',
    firstName: 'Ayşe',
    lastName: 'Türk',
    userType: 'pt',
    avatar: makeAvatar('Ayşe Türk'),
    createdAt: new Date('2023-03-20'),
    bio: 'Yoga ve bütünsel beslenme felsefesini birleştiren holistik sağlık koçuyum. 5 yıllık deneyimimle müşterilerime zihin-beden bütünlüğünü kazandırıyor, sağlıklı yaşam tarzı alışkanlıkları edinmelerine rehberlik ediyorum.',
    specializations: ['yoga', 'nutrition'] as Specialization[],
    certificates: 'RYT-200 Yoga Alliance, IIN Health Coach, Ayurveda Wellness Consultant',
    experienceYears: 5,
    packages: makePackages(
      'pt_ayse',
      1100, 2200, 4000,
      ['Başlangıç yoga programı', 'Haftada 2 online seans', 'Sağlıklı beslenme rehberi', 'Meditasyon giriş kiti'],
      ['Kişisel yoga & beslenme programı', 'Haftada 3 canlı seans', 'Holistik sağlık değerlendirmesi', 'Kişisel meditasyon rutini', 'Haftalık görüşme'],
      ['Premium Holistik Koçluk', 'Haftada 5 birebir seans', 'Ayurveda beslenme & yaşam tarzı programı', 'Nefes çalışması & meditasyon', '7/24 destek', 'Aylık bütünsel değerlendirme'],
      2, 3, 5,
    ),
    rating: 4.7,
    reviewCount: 41,
    students: Array.from({ length: 4 }, (_, i) => `student_ay${i}`),
    maxStudents: 10,
    isAvailable: true,
    background: '',
    philosophy: '',
    profilePhotos: [],
    gallery: makeGallery('ayse'),
    reviews: [
      {
        id: 'rev_ay1',
        athleteId: 'ath23',
        athleteName: 'Büşra Demir',
        athleteAvatar: makeAvatar('Büşra Demir'),
        rating: 5,
        comment: 'Ayşe hoca hem yoga hem de beslenme konusunda çok kapsamlı bir yaklaşım sunuyor. Kendimi çok iyi hissediyorum.',
        createdAt: new Date('2024-03-14'),
      },
      {
        id: 'rev_ay2',
        athleteId: 'ath24',
        athleteName: 'Selim Çetin',
        athleteAvatar: makeAvatar('Selim Çetin'),
        rating: 5,
        comment: 'Stres yönetimi konusunda da çok destekleyici. Sadece fitness değil, hayat kalitem arttı.',
        createdAt: new Date('2024-02-20'),
      },
      {
        id: 'rev_ay3',
        athleteId: 'ath25',
        athleteName: 'Gamze Kılıç',
        athleteAvatar: makeAvatar('Gamze Kılıç'),
        rating: 4,
        comment: 'Fiyatı uygun, kalitesi yüksek. Sabah yoga seansları günümü çok iyi başlatıyor.',
        createdAt: new Date('2024-01-05'),
      },
    ],
  },
];

export const MOCK_ATHLETE: Athlete = {
  id: 'athlete_devrim',
  email: 'devrimsporcu@test.com',
  firstName: 'Devrim',
  lastName: 'Sporcu',
  userType: 'athlete',
  avatar: makeAvatar('Devrim Sporcu'),
  createdAt: new Date('2024-01-01'),
  age: 28,
  gender: 'male',
  fitnessGoal: 'gain_muscle',
  experienceLevel: 'beginner',
  activePTId: undefined,
  notes: '',
};

export const MOCK_PT_USER: PT = MOCK_PTS[0];

export const TEST_CREDENTIALS = {
  athlete: { email: 'devrimsporcu@test.com', password: '123456' },
  pt: { email: 'devrimpt@test.com', password: '123456' },
};

export const MOTIVATION_QUOTES = [
  'Bugün başladığın yolculuk, yarınki seni şekillendirir.',
  'Her tekrar, hedefine bir adım daha yaklaştırıyor.',
  'Güçlü bir vücut, güçlü bir zihinle başlar.',
  'Vazgeçme! Değişim zaman alır, ama gerçekleşir.',
  'Dünkünden daha iyi olmak tek hedefin olsun.',
];

export const GOAL_LABELS: Record<string, string> = {
  lose_weight: 'Kilo Vermek',
  gain_muscle: 'Kas Geliştirmek',
  stay_fit: 'Fit Kalmak',
  healthy_life: 'Sağlıklı Yaşam',
};

export const EXPERIENCE_LABELS: Record<string, string> = {
  beginner: 'Başlangıç',
  intermediate: 'Orta Seviye',
  advanced: 'İleri Seviye',
};

export const SPECIALIZATION_LABELS: Record<string, string> = {
  weight_loss: 'Kilo Verme',
  muscle_gain: 'Kas Geliştirme',
  functional: 'Fonksiyonel',
  yoga: 'Yoga',
  pilates: 'Pilates',
  nutrition: 'Beslenme',
  rehabilitation: 'Rehabilitasyon',
};

export const PACKAGE_LEVEL_LABELS: Record<string, string> = {
  starter: 'Başlangıç',
  intermediate: 'Orta Seviye',
  professional: 'Profesyonel',
};
